---
#- name: Harden Debian 11
#  hosts: all
#  become: true
#  tasks:
#    - include_tasks: tasks/main.yml
#  handlers:
#    - include_tasks: handlers/main.yml
#  roles:
#     - role: "{{ playbook_dir }}"

- name: Harden Debian 11
  hosts: localhost
  become: true
  roles:
    - role: "{{ playbook_dir }}"
  handlers:
    - include_tasks: handlers/main.yml     
